version: "3.7"

services:
    backend:
        build: data
        command: sh -c "flask run"
        ports:
            - "5000:5000"
        working_dir: /code
        volumes:
            - ./data/:/code
        secrets:
            - client_secret
            - client_id
    redis:
        image: "redis:alpine"
    #lean:
        #image: "quantconnect/lean"

secrets:
    client_secret:
        file: ./client_secret.json
    client_id:
        file: ./client_id.txt